<script setup>
import { computed } from 'vue';
import {
    faBars,
    faArrowDown,
    faArrowUpRightFromSquare,
    faBolt,
    faBug,
    faCalendarDays,
    faChartColumn,
    faChevronLeft,
    faChevronRight,
    faChevronDown,
    faCircleCheck,
    faCircleDot,
    faCircleExclamation,
    faCircleQuestion,
    faCopy,
    faClock,
    faComments,
    faDownload,
    faDiagramProject,
    faEnvelope,
    faFileLines,
    faGift,
    faHeadset,
    faHouse,
    faKey,
    faLink,
    faLock,
    faListCheck,
    faMagnifyingGlass,
    faMoon,
    faPaperPlane,
    faPlus,
    faQrcode,
    faReceipt,
    faServer,
    faShieldHalved,
    faSliders,
    faStamp,
    faTableColumns,
    faTerminal,
    faTicket,
    faUsers,
    faWallet,
    faWandMagicSparkles,
    faWaveSquare,
    faWrench,
    faXmark,
    faArrowRight,
    faSun,
} from '@fortawesome/free-solid-svg-icons';

const props = defineProps({
    name: {
        type: String,
        default: 'circle',
    },
});

const iconDefinition = computed(() => {
    const icons = {
        activity: faWaveSquare,
        arrowDown: faArrowDown,
        arrowUpRight: faArrowUpRightFromSquare,
        arrowRight: faArrowRight,
        bars: faBars,
        bolt: faBolt,
        bug: faBug,
        calendar: faCalendarDays,
        chart: faChartColumn,
        chat: faComments,
        chevronLeft: faChevronLeft,
        chevronRight: faChevronRight,
        chevronDown: faChevronDown,
        circleCheck: faCircleCheck,
        circle: faCircleDot,
        circleExclamation: faCircleExclamation,
        circleQuestion: faCircleQuestion,
        clock: faClock,
        close: faXmark,
        copy: faCopy,
        dashboard: faTableColumns,
        download: faDownload,
        gift: faGift,
        headset: faHeadset,
        home: faHouse,
        key: faKey,
        link: faLink,
        lock: faLock,
        log: faFileLines,
        message: faEnvelope,
        moon: faMoon,
        nodes: faDiagramProject,
        plus: faPlus,
        qrcode: faQrcode,
        receipt: faReceipt,
        search: faMagnifyingGlass,
        send: faPaperPlane,
        server: faServer,
        shield: faShieldHalved,
        sliders: faSliders,
        spark: faWandMagicSparkles,
        stamp: faStamp,
        tasks: faListCheck,
        terminal: faTerminal,
        ticket: faTicket,
        users: faUsers,
        wallet: faWallet,
        wrench: faWrench,
        sun: faSun,
    };

    return icons[props.name] ?? icons.circle;
});
</script>

<template>
    <FontAwesomeIcon :icon="iconDefinition" aria-hidden="true" />
</template>
